# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME 

font_family      CodeNewRoman Nerd Font Mono
bold_font        CodeNewRoman Nerd Font Mono Bold
italic_font      CodeNewRoman Nerd Font Mono Italic
bold_italic_font CodeNewRoman Nerd Font Mono Bold Italic

font_size 14
background_opacity 0.85

# Padding horizontal (izquierda y derecha)
window_padding_width 10

# Padding vertical (arriba y abajo)
window_padding_height 10

# Tab style
tab_bar_margin_width      9
tab_bar_margin_height     9 0
tab_bar_style             separator
tab_bar_min_tabs          1
tab_separator             ""

tab_title_template        "{fmt.fg._5c6370}{fmt.bg.default}{fmt.fg._abb2bf}{fmt.bg._5c6370}{index} ⌘ {title[:15] + (title[15:] and '…')}{fmt.fg._5c6370}{fmt.bg.default} "


active_tab_title_template "{fmt.fg._33ccff}{fmt.bg.default}{fmt.fg._282c34}{fmt.bg._33ccff}{index} ⌘ {fmt.noitalic}{title[:100] + (title[100:] and '…')}{fmt.fg._33ccff}{fmt.bg.default} "

shell /usr/bin/zsh

# resize key shortcuts
map ctrl+left  resize_window narrower
map ctrl+right resize_window wider
map ctrl+up    resize_window taller
map ctrl+down  resize_window shorter
